// Public homepage copy. Detailed semantics and proof workflows live in the docs.
export const homeCopy = {
  eyebrow: 'TRITON KERNELS · LEAN 4',
  titleLead: 'Formal Verification',
  titleAccent: 'for Triton Kernels.',
  intro: 'Write Triton-style kernels, specify their behavior, and prove correctness in Lean.',
  primary: 'Documentation', secondary: 'View on GitHub',
  meta: ['Open source', 'MIT licensed', 'Built on Lean 4'],
  exampleLabel: 'Explore an example', kernelTab: 'Kernel', proofTab: 'Proof',
  demoTitle: 'VectorAdd verification example',
  demoIntro: 'Switch the operation below. The specification still requires addition.',
  original: 'Original (+)', mutated: 'Change to (−)', variantLabel: 'Choose a kernel variant',
  sampleLabel: 'ONE TILE · FOUR LANES', actual: 'Output', expected: 'Expected',
  match: 'All four lanes match.', mismatch: 'All four lanes differ from the specification.',
  verified: 'Proof checked', rejected: 'Proof does not close',
  verifiedText: 'Lean checks the general addition proof under the stated preconditions.',
  rejectedText: 'The same proof fails after changing addition to subtraction.',
  recorded: 'Recorded Lean checks', recordNote: 'Two fixed variants, checked ahead of time. The four sample values are also proved from the DSL semantics.',
  proofDetails: 'Inspect the proof and Lean output', diagnosticLabel: 'Lean output',
  reproduction: 'Reproduce these checks', sampleNote: 'The values illustrate one input. The addition theorem covers every input allowed by its preconditions.',
  demoNoScript: 'Enable JavaScript to switch variants, or inspect the source and recorded checks below.',
  copy: 'Copy code', copied: 'Copied', copyFailed: 'Select the code to copy',
  sourceLink: 'Full source', exampleTitle: 'Elementwise vector addition',
  contractLabel: 'THE CONTRACT',
  guarantees: ['Each output equals the sum of its inputs.', 'Execution terminates.', 'Memory outside the output window is preserved.'],
  exampleScope: 'Aligned tiles, mathematical values, and the stated memory preconditions.',
  exampleNote: 'Excerpts from the complete Lean example.',
  scopeLink: 'Supported Triton subset',
  features: [
    { symbol: '{ }', title: 'Write familiar kernels', text: 'Express loads, stores, masks, and tile operations in a typed Triton-style DSL.', link: 'Explore the language', href: 'cookbook/' },
    { symbol: '⊨', title: 'State what correctness means', text: 'Specify mathematical outputs or show that two kernels agree, with assumptions made explicit.', link: 'Read the contract guide', href: 'proofs/correctness-surfaces/' },
    { symbol: 'λ', title: 'Build proofs in Lean', text: 'Reuse the lemma library and agent tooling to construct proofs that Lean can check.', link: 'Explore proof tooling', href: 'overview/#proof-automation' },
  ],
  resultsTitle: 'Kernel verification examples',
  resultsIntro: 'Follow a result from its specification to the Lean source.',
  allExamples: 'All examples',
  examples: [
    { title: 'Log-sum-exp', kind: 'Mathematical correctness', text: 'Per-block reductions, active lanes, and masked tails.', source: 'bench/tritonbench_g/logsumexp_fwd/LogsumexpFwd.lean', file: 'LogsumexpFwd.lean' },
    { title: 'Fused SiLU', kind: 'Kernel equivalence', text: 'Fused and staged implementations under an explicit rounding model.', source: 'bench/examples/FusedSiLUEquiv.lean', file: 'FusedSiLUEquiv.lean' },
    { title: 'FlashAttention', kind: 'Algorithm refinement', text: 'Tiled attention against a mathematical reference, with causal and boundary cases.', source: 'VeriTile/Examples/FlashAttention1/NaiveRefinement.lean', file: 'NaiveRefinement.lean' },
  ],
  corpusTitle: 'TritonBench-G', pairedLabel: 'paired Python / Lean ports',
  corpusText: 'Browse the corpus, theorem contracts, and audit records.',
  corpusLink: 'View benchmark status', corpusNote: 'Source inventory; proof scope is recorded per kernel.',
  further: 'From the project', roadmapLink: 'Development roadmap',
  closingTitle: 'Getting started',
  closingText: 'Build the library, then check the complete VectorAdd example.',
  quickPrerequisite: 'With Git and elan installed; elan uses the pinned Lean toolchain.',
  quickExpected: 'Expected: exit 0, with the axiom and statement-surface checks passing.',
  setupGuide: 'Setup guide',
  gettingStarted: 'Get started', browseSource: 'Browse the source',
};
