// The project's contributions and their evidence, adapted from the deck.
export const homeStory = {
  intro: 'VeriTile embeds Triton in Lean 4 for kernel verification, with explicit semantics, mathematical specifications, and proof generation using agents.',
  promise: 'Theorems cover inputs and parameters that satisfy their stated preconditions.',
  pillars: [
    { label: 'Triton embedded in Lean', href: '#language', symbol: '{ }' },
    { label: 'Correctness & equivalence', href: '#proofs', symbol: '≡' },
    { label: 'Proof generation', href: '#agents', symbol: 'λ' },
  ],
  languageTitle: 'Triton embedded in Lean',
  languageLead: 'VeriTile embeds Triton in Lean, so users can',
  languageEmphasis: 'write kernels in Triton syntax without learning Lean',
  languageText: 'The framework automatically handles the formal representation and execution semantics used for verification.',
  pythonLabel: 'TRITON KERNEL', leanLabel: 'INTERNAL LEAN REPRESENTATION',
  pythonRole: 'Written by the kernel author', leanRole: 'Used internally for verification',
  languageNote: 'Aligned vector addition (no masked tail). Names matched for comparison.',
  languageLink: 'Supported syntax',
  proofTitle: 'Kernel correctness and equivalence',
  proofText: 'Verify computation and memory effects against a specification or a reference implementation.',
  computationLabel: 'Computation', memoryLabel: 'Memory', proofExampleLabel: 'Example',
  proofDetailsLabel: 'Proof details', proofLink: 'View proof',
  proofRelationNote: 'Schematic notation. See Proof details for scope and View proof for the Lean source.',
  proofCards: [
    {
      id: 'correctness', label: 'KERNEL → SPECIFICATION', title: 'Correctness',
      description: 'A kernel’s output values and memory effects match its specification.',
      relationLeft: 'lse_kernel', relationOperator: '⊨', relationRight: 'lse_spec',
      computation: 'Outputs equal the mathematical function defined by the specification.',
      memory: 'Results occupy the specified output addresses. Memory outside the declared write regions is preserved.',
      example: 'Log-sum-exp',
      exampleText: 'The LSE kernel stores the specified reduction result at each declared output address.',
      formulaLeft: 'out', formulaRight: 'log Σ exp(xᵢ)',
      formulaLabel: 'Output equals the logarithm of the sum of exponentials over active lanes',
      exampleCaption: 'The formula shown omits input scaling and sums over the active lanes of one block.',
      scope: 'Arithmetic is modeled over real numbers. For admissible block widths and row lengths, the kernel terminates with the specified value at its output address and leaves every other memory cell unchanged. Active reads and the output store must be in bounds.',
      source: 'bench/tritonbench_g/logsumexp_fwd/LogsumexpFwd.lean',
    },
    {
      id: 'equivalence', label: 'KERNEL ↔ KERNEL', title: 'Equivalence',
      description: 'Two kernels agree on output values and observable memory effects.',
      relationLeft: 'direct_lse', relationOperator: '≡', relationRight: 'stable_lse',
      computation: 'Outputs equal those of the other implementation under the same numerical model.',
      memory: 'Both kernels agree at the specified output addresses. Memory outside the declared write regions is preserved.',
      example: 'Direct and stable log-sum-exp',
      exampleText: 'The direct and stable LSE kernels store equal reduction results at each declared output address.',
      formulaLeft: 'log Σ exp(xᵢ)', formulaRight: 'm + log Σ exp(xᵢ − m)',
      formulaLabel: 'Direct log-sum-exp equals the maximum-shifted log-sum-exp',
      exampleCaption: 'The stable form subtracts m, the maximum input value in a nonempty block.',
      scope: 'Intermediate arithmetic is modeled over real numbers. Both kernels round only at the final bf16 store, using the same model R. For a nonempty block with input and output windows in bounds, both terminate from the same state, agree at y[pid], and leave every other memory cell unchanged.',
      source: 'bench/examples/StableLogSumExpEquiv.lean',
    },
  ],
  tryLabel: 'VectorAdd example', tryText: 'Compare the original kernel and a subtraction variant using recorded Lean checks.',
  agentTitle: 'Proof generation with agents',
  agentText: 'The agent uses VeriTile’s reusable lemmas to construct candidate proofs and revises them with feedback from Lean.',
  lemmaTitle: 'Reusable lemmas',
  lemmaText: 'Shared proofs for mathematical operations and memory access patterns.',
  lemmaGroups: [
    { title: 'Loop invariants', text: 'Carry a property through every loop iteration.', source: 'LoopInvariant' },
    { title: 'Matrix multiplication', text: 'Connect tile dot products to matrix sums.', source: 'Matmul' },
    { title: 'Masked stores', text: 'Prove written values and preserve untouched memory.', source: 'ScatterStore' },
    { title: 'Address calculations', text: 'Show that distinct lanes write to distinct addresses.', source: 'OffsetInjective' },
  ],
  generationTitle: 'Proof generation',
  generationText: 'Start with a kernel and its specification, then refine a proof with Lean.',
  generationInput: 'Kernel + specification',
  agentSteps: [
    { title: 'Proof agent', text: 'Select lemmas and construct a candidate proof.' },
    { title: 'Lean checker', text: 'Check the proof and report remaining goals.' },
  ],
  feedback: 'Lean diagnostics → revise the candidate',
  generationSuccess: 'WHEN THE PROOF PASSES', generationOutput: 'Checked Lean proof',
  harnessLink: 'Proving guide', trustLink: 'Proof audits',
  resultsTitle: 'FlashAttention and benchmark coverage',
  resultsText: 'The following artifacts include forward FlashAttention contracts and a benchmark corpus with per-kernel audit records.',
  attentionLabel: 'FEATURED PROOF · FLASHATTENTION',
  attentionTitle: 'FlashAttention Forward',
  attentionText: 'The forward contracts relate tiled, online-softmax attention to a direct attention reference. They cover causal and non-causal variants, with boundary and D-tail conditions.',
  attentionParts: ['Streaming softmax', 'Online rescaling', 'Tiling', 'Causal masking', 'Boundary & D-tail'],
  attentionLink: 'Read the FlashAttention proof', allExamples: 'Browse all examples',
  corpusTitle: 'TritonBench-G', ports: 'paired Python / Lean ports', statements: 'tracked theorem statements',
  corpusText: 'The completion audit records port compilation, placeholder scans, and translation checks. Per-kernel contracts and remaining gaps are linked.',
  corpusNote: 'Source and manifest counts; proof scope is recorded per theorem.',
  auditLink: 'Read the completion audit', coverageLink: 'Inspect proof coverage',
};
