name = "veritile-overview"
defaultTargets = ["VeriTileOverview", "VeriTileSite"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[lean_lib]]
name = "VeriTileOverview"

[[lean_lib]]
name = "VeriTileSite"

[[lean_exe]]
name = "veritile-overview"
root = "Main"
