/-
VeriTile.ExternalCheck

Proof-surface contracts for externally checked compute-to-algorithm gaps.
-/

import VeriTile.Core

namespace VeriTile

/-! ## External compute-gap contracts -/

/-- Which public theorem surface a gap contract is attached to. -/
inductive GapKind where
  | correct
  | refine
  deriving DecidableEq, Repr

/--
How an external checker compares the compute-facing behavior against the
projected algorithm behavior.

`relational` names a checker-defined relation for cases that are not naturally
expressed as pointwise exact or epsilon comparisons.
-/
inductive GapComparison where
  | exact
  | approx (atol rtol : ℝ)
  | relational (name : String)

/-- Named input domain used by the external checker. -/
structure InputDomain where
  name : String
  deriving Repr

/--
External contract for the compute-to-algorithm gap induced by
`ComputeKernel.toAlgorithm?` / dtype erasure.

The first checker implementation is intentionally outside Lean. This structure
records the contract that such a checker validates.
-/
structure ComputeGapContract where
  name : String
  kind : GapKind
  comparison : GapComparison
  inputDomain : InputDomain

/--
Trusted evidence that the external checker validated a compute-gap contract.

This is an opaque proposition rather than a Lean implementation of the checker:
callers may keep the gap ignored, or explicitly require this token when they
want a theorem surface to record an external validation obligation.
-/
opaque ExternalChecked : ComputeGapContract → Prop

/--
Whether a compute-facing theorem ignores the compute-to-algorithm gap or
requires externally checked evidence for it.
-/
inductive GapPolicy where
  | ignore
  | require (contract : ComputeGapContract)

namespace GapPolicy

/-- The Lean-side obligation generated by a gap policy. -/
def Holds : GapPolicy → Prop
  | .ignore => True
  | .require contract => ExternalChecked contract

@[simp] theorem holds_ignore : Holds .ignore := by
  trivial

@[simp] theorem holds_require (contract : ComputeGapContract) :
    Holds (.require contract) = ExternalChecked contract := rfl

end GapPolicy

end VeriTile
