/-
Correctness is mathematical (`Real`). Implementation equivalence is a formal
derivation under atom assumptions admitted by two-gates (`FloatingPoint`).
The evidence is attached to atoms, not to the whole equivalence theorem.
This module supplies the proof calculus, not a numerical experiment runner.
-/
import Lean.Data.Json

namespace VeriTile.Spec

/-- A reader-facing ideal mathematical specification. Existing unwrapped
headlines remain supported; this wrapper makes the intended meaning explicit. -/
def Real (claim : Prop) : Prop := claim

inductive GateStatus where
  | notRun | pass | warn | fail | inconclusive
  deriving Repr, DecidableEq, BEq

def GateStatus.label : GateStatus → String
  | .notRun => "NOT_RUN"
  | .pass => "PASS"
  | .warn => "WARN"
  | .fail => "FAIL"
  | .inconclusive => "INCONCLUSIVE"

inductive WarningPolicy where
  | passOnly | allowWarn
  deriving Repr, DecidableEq, BEq

/-- Frozen configuration from the experiment registry, or explicitly identified
published-report metadata. A summary import does not invent missing lowering
digests. This records how the atom was selected; experimental dimensions do
not constrain a later symbolic derivation under the selected assumption.
A supplied hash alone proves nothing about a GPU execution. -/
structure Contract where
  ruleID : String
  instanceKey : String
  configuration : Lean.Json
  warningPolicy : WarningPolicy
  /-- Human-readable frozen scope; full machine-readable data stays above. -/
  description : String := ""

/-- A numerical atomic rewrite, instantiated as syntax fragments. The contract
records the experiment used to select the assumption, including precision,
shape, backend, operand distribution and protocol. Syntax dimensions may be
symbolic; the derivation does not equate them with the experimental shape. -/
structure AtomicRule (Statement : Type u) where
  lhs : List Statement
  rhs : List Statement
  contract : Contract

/-- A result summary, not proof of an experiment. Pending records have no
artifact and neither gate has run. Provenance/replay is a separate obligation. -/
structure Evidence where
  instanceKey : String
  artifact : Option String := none
  bias : GateStatus := .notRun
  vars : GateStatus := .notRun
  deriving Repr

def GateStatus.allowed (policy : WarningPolicy) : GateStatus → Bool
  | .pass => true
  | .warn => policy == .allowWarn
  | _ => false

def PolicyAllows (policy : WarningPolicy) (e : Evidence) : Prop :=
  e.bias.allowed policy = true ∧ e.vars.allowed policy = true

/-- External admission of this atomic modeling assumption from numerical
evidence. A model importing a trusted report carries this as a scoped premise;
its syntax template can be instantiated at symbolic dimensions independently
of experimental dimensions. Lean checks the derivation under that premise,
not a universal statistical guarantee or the external GPU experiment.
No Boolean-to-proof conversion or introduction axiom is provided. -/
opaque EvidenceValidated {Statement : Type u}
    (rule : AtomicRule Statement) (e : Evidence) : Prop

/-- A rule-table row. Pending rows are data, not available proof assumptions. -/
structure RuleEntry (Statement : Type u) where
  rule : AtomicRule Statement
  evidence : Evidence

/-- Permission to use ONE experimentally checked atom as an equivalence
assumption. It asserts neither IEEE equality nor a measured whole-kernel result. -/
structure AcceptedAtom {Statement : Type u} (entry : RuleEntry Statement) : Prop where
  validated : EvidenceValidated entry.rule entry.evidence
  instanceMatches : entry.evidence.instanceKey = entry.rule.contract.instanceKey
  artifactPresent : entry.evidence.artifact.isSome = true
  gates : PolicyAllows entry.rule.contract.warningPolicy entry.evidence

abbrev Assumptions (Statement : Type u) := List (RuleEntry Statement)

def AcceptedAssumptions {Statement : Type u} (assumptions : Assumptions Statement) : Prop :=
  ∀ entry ∈ assumptions, AcceptedAtom entry

/-- The formal equational theory generated by accepted atoms. Symmetry,
transitivity and common syntactic context are proof rules of THIS theory;
they do not assert that statistical gate decisions compose or reverse.
There is deliberately no elimination rule to IEEE value equality. -/
inductive Derivation {Statement : Type u} (assumptions : Assumptions Statement) :
    List Statement → List Statement → Prop where
  | refl (code) : Derivation assumptions code code
  | atom (entry : RuleEntry Statement) (member : entry ∈ assumptions)
      (accepted : AcceptedAtom entry) :
      Derivation assumptions entry.rule.lhs entry.rule.rhs
  | symm {lhs rhs} : Derivation assumptions lhs rhs → Derivation assumptions rhs lhs
  | trans {lhs middle rhs} : Derivation assumptions lhs middle →
      Derivation assumptions middle rhs → Derivation assumptions lhs rhs
  | frame (beforeCode afterCode : List Statement) {lhs rhs} :
      Derivation assumptions lhs rhs →
      Derivation assumptions (beforeCode ++ lhs ++ afterCode) (beforeCode ++ rhs ++ afterCode)

/-- Auditable syntax view for a sequential implementation. The signature must
retain all metadata outside the statement sequence (e.g. inputs and outputs).
This is a syntax interface, not a numerical execution or hardware model. -/
class ProgramSyntax (Program : Type u) where
  Statement : Type u
  Signature : Type u
  signature : Program → Signature
  body : Program → List Statement
  /-- Optional, library-defined structural equivalence. It must preserve
  numerical primitives without assuming their algebraic laws. IO views can
  supply an independently proved abstract-execution relation, including
  termination and memory framing. The default permits only syntax rules. -/
  structural : Option (Program → Program → Prop) := none
  /-- Optional library-defined execution steps whose output expressions have
  derivations in the selected atomic theory. As with structural steps, the
  relation must require successful runs and preserve public observations. -/
  numerical : Assumptions Statement → Program → Program → Prop := fun _ _ _ => False
  /-- Additional context preserved by syntax-only steps in a structural view,
  such as private scratch declarations. A structural execution proof may
  relate different private workspaces; a mere body rewrite may not. -/
  sameContext : Program → Program → Prop := fun _ _ => True

instance {Statement : Type u} : ProgramSyntax (List Statement) where
  Statement := Statement
  Signature := PUnit
  signature := fun _ => PUnit.unit
  body := id

/-- Composition of syntax derivations and certified whole-program structural
steps. Every step retains the public signature. Structural IO equivalence is
not lifted through an arbitrary statement context: its private memory and
register observations need not be preserved by such a context. -/
inductive ProgramDerivation {Program : Type u} [view : ProgramSyntax Program]
    (structural : Program → Program → Prop) (assumptions : Assumptions view.Statement) :
    Program → Program → Prop where
  | refl (program) : ProgramDerivation structural assumptions program program
  | syntax {lhs rhs} (signature : view.signature lhs = view.signature rhs)
      (context : view.sameContext lhs rhs)
      (proof : Derivation assumptions (view.body lhs) (view.body rhs)) :
      ProgramDerivation structural assumptions lhs rhs
  | structural {lhs rhs} (signature : view.signature lhs = view.signature rhs)
      (proof : structural lhs rhs) : ProgramDerivation structural assumptions lhs rhs
  | numerical {lhs rhs} (signature : view.signature lhs = view.signature rhs)
      (proof : view.numerical assumptions lhs rhs) :
      ProgramDerivation structural assumptions lhs rhs
  | symm {lhs rhs} : ProgramDerivation structural assumptions lhs rhs →
      ProgramDerivation structural assumptions rhs lhs
  | trans {lhs middle rhs} : ProgramDerivation structural assumptions lhs middle →
      ProgramDerivation structural assumptions middle rhs →
      ProgramDerivation structural assumptions lhs rhs

/-- Existing syntax-only views keep precisely their original derivation type.
An IO view may additionally enable certified structural program steps. -/
def ProgramSyntax.Derivation {Program : Type u} [view : ProgramSyntax Program]
    (assumptions : Assumptions view.Statement) (lhs rhs : Program) : Prop :=
  match view.structural with
  | none => Spec.Derivation assumptions (view.body lhs) (view.body rhs)
  | some structural => ProgramDerivation structural assumptions lhs rhs

/-- Floating-point IMPLEMENTATION EQUIVALENCE under the displayed atom
assumptions, written `lhs ≡[R] rhs` on the public surface. Correctness against
a mathematical formula stays in `Real`. Atomic checks authorize assumptions;
Lean checks the resulting derivation. -/
structure FloatingPoint {Program : Type u} [view : ProgramSyntax Program]
    (assumptions : Assumptions view.Statement) (lhs rhs : Program) : Prop where
  sameSignature : view.signature lhs = view.signature rhs
  derivation : ProgramSyntax.Derivation assumptions lhs rhs

/-- Reuse the existing equivalence spelling. Here `R` supplies the atomic rule
table; models can coerce to their table to keep experiment bookkeeping out of
the headline. Open `VeriTile.Spec` to select this meaning; historical KernelIO
scopes retain their original abstract-rounding interpretation. -/
abbrev Equiv {Program : Type u} [view : ProgramSyntax Program]
    (lhs rhs : Program) (R : Assumptions view.Statement) : Prop := FloatingPoint R lhs rhs

@[inherit_doc] scoped notation:25 lhs " ≡[" R "] " rhs => Equiv lhs rhs R

namespace FloatingPoint

variable {Program : Type u} [view : ProgramSyntax Program]
    {assumptions : Assumptions view.Statement} {lhs middle rhs : Program}

theorem ofDerivation (hsig : view.signature lhs = view.signature rhs)
    (hcontext : view.sameContext lhs rhs)
    (h : Derivation assumptions (view.body lhs) (view.body rhs)) :
    FloatingPoint assumptions lhs rhs := by
  refine ⟨hsig, ?_⟩
  unfold ProgramSyntax.Derivation
  cases view.structural with
  | none => exact h
  | some _ => exact .syntax hsig hcontext h

theorem ofStructural {structural : Program → Program → Prop}
    (hview : view.structural = some structural)
    (hsig : view.signature lhs = view.signature rhs) (h : structural lhs rhs) :
    FloatingPoint assumptions lhs rhs := by
  refine ⟨hsig, ?_⟩
  simp only [ProgramSyntax.Derivation, hview]
  exact .structural hsig h

theorem ofNumerical {structural : Program → Program → Prop}
    (hview : view.structural = some structural)
    (hsig : view.signature lhs = view.signature rhs)
    (h : view.numerical assumptions lhs rhs) : FloatingPoint assumptions lhs rhs := by
  refine ⟨hsig, ?_⟩
  simp only [ProgramSyntax.Derivation, hview]
  exact .numerical hsig h

theorem refl (program : Program) : FloatingPoint assumptions program program := by
  refine ⟨rfl, ?_⟩
  unfold ProgramSyntax.Derivation
  cases view.structural <;> exact .refl _

theorem symm (h : FloatingPoint assumptions lhs rhs) : FloatingPoint assumptions rhs lhs := by
  refine ⟨h.sameSignature.symm, ?_⟩
  have hd := h.derivation
  cases hs : view.structural <;>
    simp only [ProgramSyntax.Derivation, hs] at hd ⊢ <;> exact .symm hd

theorem trans (h₁ : FloatingPoint assumptions lhs middle)
    (h₂ : FloatingPoint assumptions middle rhs) : FloatingPoint assumptions lhs rhs := by
  refine ⟨h₁.sameSignature.trans h₂.sameSignature, ?_⟩
  have hd₁ := h₁.derivation
  have hd₂ := h₂.derivation
  cases hs : view.structural <;>
    simp only [ProgramSyntax.Derivation, hs] at hd₁ hd₂ ⊢ <;> exact .trans hd₁ hd₂

end FloatingPoint
end VeriTile.Spec
