/-
Correctness is mathematical (`Real`). Implementation equivalence is a formal
derivation under atom assumptions admitted by two-gates (`FloatingPoint`).
The evidence is attached to atoms, not to the whole equivalence theorem.
This module supplies the proof calculus, not a numerical experiment runner.
-/
import Lean.Data.Json

namespace VeriTile.Spec

/-- A reader-facing ideal mathematical specification. Existing unwrapped
headlines remain supported; this wrapper makes the intended meaning explicit. -/
def Real (claim : Prop) : Prop := claim

inductive GateStatus where
  | notRun | pass | warn | fail | inconclusive
  deriving Repr, DecidableEq, BEq

def GateStatus.label : GateStatus → String
  | .notRun => "NOT_RUN"
  | .pass => "PASS"
  | .warn => "WARN"
  | .fail => "FAIL"
  | .inconclusive => "INCONCLUSIVE"

inductive WarningPolicy where
  | passOnly | allowWarn
  deriving Repr, DecidableEq, BEq

/-- Frozen configuration from the experiment registry, or explicitly identified
published-report metadata. A summary import does not invent missing lowering
digests. The external assumption binds this JSON/key to the actual programs;
a supplied hash alone proves nothing about a GPU execution. -/
structure Contract where
  ruleID : String
  instanceKey : String
  configuration : Lean.Json
  warningPolicy : WarningPolicy
  /-- Human-readable frozen scope; full machine-readable data stays above. -/
  description : String := ""

/-- A numerical atomic rewrite, instantiated as syntax fragments. The contract
binds their precision, shape, backend, operand distribution and protocol.
Two-gates checks this atom; whole-program equivalence is derived separately. -/
structure AtomicRule (Statement : Type u) where
  lhs : List Statement
  rhs : List Statement
  contract : Contract

/-- A result summary, not proof of an experiment. Pending records have no
artifact and neither gate has run. Provenance/replay is a separate obligation. -/
structure Evidence where
  instanceKey : String
  artifact : Option String := none
  bias : GateStatus := .notRun
  vars : GateStatus := .notRun
  deriving Repr

def GateStatus.allowed (policy : WarningPolicy) : GateStatus → Bool
  | .pass => true
  | .warn => policy == .allowWarn
  | _ => false

def PolicyAllows (policy : WarningPolicy) (e : Evidence) : Prop :=
  e.bias.allowed policy = true ∧ e.vars.allowed policy = true

/-- External numerical acceptance for this specific atomic rule, including
syntax/configuration/backend correspondence and the chosen evidence source.
A model importing a trusted report carries this as a scoped premise. Lean
checks the derivation under that premise, not the external GPU experiment.
No Boolean-to-proof conversion or introduction axiom is provided. -/
opaque EvidenceValidated {Statement : Type u}
    (rule : AtomicRule Statement) (e : Evidence) : Prop

/-- A rule-table row. Pending rows are data, not available proof assumptions. -/
structure RuleEntry (Statement : Type u) where
  rule : AtomicRule Statement
  evidence : Evidence

/-- Permission to use ONE experimentally checked atom as an equivalence
assumption. It asserts neither IEEE equality nor a measured whole-kernel result. -/
structure AcceptedAtom {Statement : Type u} (entry : RuleEntry Statement) : Prop where
  validated : EvidenceValidated entry.rule entry.evidence
  instanceMatches : entry.evidence.instanceKey = entry.rule.contract.instanceKey
  artifactPresent : entry.evidence.artifact.isSome = true
  gates : PolicyAllows entry.rule.contract.warningPolicy entry.evidence

abbrev Assumptions (Statement : Type u) := List (RuleEntry Statement)

def AcceptedAssumptions {Statement : Type u} (assumptions : Assumptions Statement) : Prop :=
  ∀ entry ∈ assumptions, AcceptedAtom entry

/-- The formal equational theory generated by accepted atoms. Symmetry,
transitivity and common syntactic context are proof rules of THIS theory;
they do not assert that statistical gate decisions compose or reverse.
There is deliberately no elimination rule to IEEE value equality. -/
inductive Derivation {Statement : Type u} (assumptions : Assumptions Statement) :
    List Statement → List Statement → Prop where
  | refl (code) : Derivation assumptions code code
  | atom (entry : RuleEntry Statement) (member : entry ∈ assumptions)
      (accepted : AcceptedAtom entry) :
      Derivation assumptions entry.rule.lhs entry.rule.rhs
  | symm {lhs rhs} : Derivation assumptions lhs rhs → Derivation assumptions rhs lhs
  | trans {lhs middle rhs} : Derivation assumptions lhs middle →
      Derivation assumptions middle rhs → Derivation assumptions lhs rhs
  | frame (beforeCode afterCode : List Statement) {lhs rhs} :
      Derivation assumptions lhs rhs →
      Derivation assumptions (beforeCode ++ lhs ++ afterCode) (beforeCode ++ rhs ++ afterCode)

/-- Auditable syntax view for a sequential implementation. The signature must
retain all metadata outside the statement sequence (e.g. inputs and outputs).
This is a syntax interface, not a numerical execution or hardware model. -/
class ProgramSyntax (Program : Type u) where
  Statement : Type u
  Signature : Type u
  signature : Program → Signature
  body : Program → List Statement

instance {Statement : Type u} : ProgramSyntax (List Statement) where
  Statement := Statement
  Signature := PUnit
  signature := fun _ => PUnit.unit
  body := id

/-- Floating-point IMPLEMENTATION EQUIVALENCE under the displayed atom
assumptions, written `lhs ≡[R] rhs` on the public surface. Correctness against
a mathematical formula stays in `Real`. Atomic checks authorize assumptions;
Lean checks the resulting derivation. -/
structure FloatingPoint {Program : Type u} [view : ProgramSyntax Program]
    (assumptions : Assumptions view.Statement) (lhs rhs : Program) : Prop where
  sameSignature : view.signature lhs = view.signature rhs
  derivation : Derivation assumptions (view.body lhs) (view.body rhs)

/-- Reuse the existing equivalence spelling. Here `R` supplies the atomic rule
table; models can coerce to their table to keep experiment bookkeeping out of
the headline. Open `VeriTile.Spec` to select this meaning; historical KernelIO
scopes retain their original abstract-rounding interpretation. -/
abbrev Equiv {Program : Type u} [view : ProgramSyntax Program]
    (lhs rhs : Program) (R : Assumptions view.Statement) : Prop := FloatingPoint R lhs rhs

@[inherit_doc] scoped notation:25 lhs " ≡[" R "] " rhs => Equiv lhs rhs R

namespace FloatingPoint

variable {Program : Type u} [view : ProgramSyntax Program]
    {assumptions : Assumptions view.Statement} {lhs middle rhs : Program}

theorem refl (program : Program) : FloatingPoint assumptions program program :=
  ⟨rfl, .refl _⟩

theorem symm (h : FloatingPoint assumptions lhs rhs) : FloatingPoint assumptions rhs lhs :=
  ⟨h.sameSignature.symm, .symm h.derivation⟩

theorem trans (h₁ : FloatingPoint assumptions lhs middle)
    (h₂ : FloatingPoint assumptions middle rhs) : FloatingPoint assumptions lhs rhs :=
  ⟨h₁.sameSignature.trans h₂.sameSignature, .trans h₁.derivation h₂.derivation⟩

end FloatingPoint
end VeriTile.Spec
