/- Expression congruence generated by admitted scalar FP atoms.
The reduction theorem below preserves every leaf, including explicit padding;
it does not assume a floating zero identity or a whole-reduction rule. -/
import VeriTile.Triton.Float.Structural
import VeriTile.Spec

namespace VeriTile.Triton.FP.Equational

/-- Exact scalar templates used when instantiating the fp32 addition laws. -/
def scalarRef (name : RegName) : Op .real [] := .ref .real [] name

def plus (a b : Op .real []) : Op .real [] := .add .real .nil a b

def fragment (e : Op .real []) : List ComputeStmt :=
  [.assign .real [] "out" (.compute (.alg .fp32 e))]

def commuteLHS := fragment (plus (scalarRef "a") (scalarRef "b"))
def commuteRHS := fragment (plus (scalarRef "b") (scalarRef "a"))
def associateLHS := fragment (plus (plus (scalarRef "a") (scalarRef "b")) (scalarRef "c"))
def associateRHS := fragment (plus (scalarRef "a") (plus (scalarRef "b") (scalarRef "c")))

/-- Numerical call labels keep precision and dtype. Opaque operation labels
may be extended without giving their operations any algebraic laws. -/
inductive Symbol where
  | literal (precision : Option ComputeDType) (dtype : FloatDType) (value : ℝ)
  | negInf
  | binary (precision : Option ComputeDType) (dtype : FloatDType) (op : Structural.Binary)
  | unary (precision : Option ComputeDType) (op : Structural.Unary)
  | cast (precision : Option ComputeDType) (source target : FloatDType)
  | fromNat (precision : Option ComputeDType) (value : Nat)
  | fromInt (precision : Option ComputeDType) (value : Int)
  | fp32Bits (bits : Float32Bits)
  | fp32Load
  | reduceMax (precision : Option ComputeDType) (shape : TileShape)
      (axis : Fin shape.length) (keepDims : Bool)
      (outputIndex : TileIndex (TileShape.reduceShape shape axis keepDims))

inductive Term (α : Type) where
  | leaf (value : α)
  | app (op : Symbol) (args : List (Term α))

instance [Inhabited α] : Inhabited (Term α) := ⟨.leaf default⟩

def Term.add (a b : Term α) : Term α :=
  .app (.binary (some .fp32) .real .add) [a, b]

def Term.evaluate (leaf : α → β) (app : Symbol → List β → β) : Term α → β
  | .leaf a => leaf a
  | .app op args => app op (args.map (Term.evaluate leaf app))

/-- Scalar substitution and ordinary expression congruence. The two numerical
constructors require proofs of the exact scalar templates in the selected
statement theory; neither constructor supplies a new admitted assumption. -/
inductive TermEq (R : Spec.Assumptions ComputeStmt) : Term α → Term α → Prop where
  | refl (a) : TermEq R a a
  | symm {a b} : TermEq R a b → TermEq R b a
  | trans {a b c} : TermEq R a b → TermEq R b c → TermEq R a c
  | context (op : Symbol) (before after : List (Term α)) {a b} :
      TermEq R a b → TermEq R (.app op (before ++ a :: after)) (.app op (before ++ b :: after))
  | addCommute (h : Spec.Derivation R commuteLHS commuteRHS) (a b : Term α) :
      TermEq R (a.add b) (b.add a)
  | addAssociate (h : Spec.Derivation R associateLHS associateRHS) (a b c : Term α) :
      TermEq R ((a.add b).add c) (a.add (b.add c))

namespace TermEq
variable {R : Spec.Assumptions ComputeStmt}

theorem addCongr {a b c d : Term α} (h₁ : TermEq R a b) (h₂ : TermEq R c d) :
    TermEq R (a.add c) (b.add d) :=
  .trans (.context _ [] [c] h₁) (.context _ [b] [] h₂)

/-- Soundness in every interpretation of the selected scalar theory. The
operation interpreter is arbitrary except for the two explicitly supplied
implications; in particular it need not be a ring or have an additive zero. -/
theorem sound (leaf : α → β) (app : Symbol → List β → β)
    (hc : Spec.Derivation R commuteLHS commuteRHS → ∀ a b,
      app (.binary (some .fp32) .real .add) [a, b] =
        app (.binary (some .fp32) .real .add) [b, a])
    (ha : Spec.Derivation R associateLHS associateRHS → ∀ a b c,
      app (.binary (some .fp32) .real .add)
          [app (.binary (some .fp32) .real .add) [a, b], c] =
        app (.binary (some .fp32) .real .add)
          [a, app (.binary (some .fp32) .real .add) [b, c]])
    {a b : Term α} (h : TermEq R a b) :
    a.evaluate leaf app = b.evaluate leaf app := by
  induction h with
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | context op before after _ ih => simp only [Term.evaluate, List.map_append, List.map_cons, ih]
  | addCommute h a b =>
    simpa only [Term.add, Term.evaluate, List.map_cons, List.map_nil] using
      hc h (a.evaluate leaf app) (b.evaluate leaf app)
  | addAssociate h a b c =>
    simpa only [Term.add, Term.evaluate, List.map_cons, List.map_nil] using
      ha h (a.evaluate leaf app) (b.evaluate leaf app) (c.evaluate leaf app)

end TermEq

/-- A reduction tree has no implicit identity element. A padding zero, when
present in a lowering, is an ordinary explicit leaf and cannot disappear. -/
inductive SumTree (α : Type) where
  | leaf (value : Term α)
  | join (left right : SumTree α)

def SumTree.leaves : SumTree α → List (Term α)
  | .leaf a => [a]
  | .join a b => a.leaves ++ b.leaves

def SumTree.eval : SumTree α → Term α
  | .leaf a => a
  | .join a b => a.eval.add b.eval

/-- `none` is the absence of a subtree, not a floating zero value. -/
def combine : Option (Term α) → Option (Term α) → Option (Term α)
  | none, b => b
  | a, none => a
  | some a, some b => some (a.add b)

def OptionalEq (R : Spec.Assumptions ComputeStmt) :
    Option (Term α) → Option (Term α) → Prop
  | none, none => True
  | some a, some b => TermEq R a b
  | _, _ => False

namespace OptionalEq
variable {R : Spec.Assumptions ComputeStmt}

theorem refl (a : Option (Term α)) : OptionalEq R a a := by
  cases a with
  | none => trivial
  | some a => exact TermEq.refl a

theorem symm {a b : Option (Term α)} (h : OptionalEq R a b) : OptionalEq R b a := by
  cases a <;> cases b <;> simp only [OptionalEq] at h ⊢
  exact TermEq.symm h

theorem trans {a b c : Option (Term α)} (h₁ : OptionalEq R a b) (h₂ : OptionalEq R b c) :
    OptionalEq R a c := by
  cases a <;> cases b <;> cases c <;> simp only [OptionalEq] at h₁ h₂ ⊢
  all_goals first | contradiction | trivial | exact .trans h₁ h₂

theorem congr {a b c d : Option (Term α)} (h₁ : OptionalEq R a b) (h₂ : OptionalEq R c d) :
    OptionalEq R (combine a c) (combine b d) := by
  cases a <;> cases b <;> cases c <;> cases d <;>
    simp only [OptionalEq, combine] at h₁ h₂ ⊢
  all_goals first | contradiction | trivial | assumption | exact TermEq.addCongr h₁ h₂

theorem commute (h : Spec.Derivation R commuteLHS commuteRHS) (a b : Option (Term α)) :
    OptionalEq R (combine a b) (combine b a) := by
  cases a <;> cases b <;> simp only [combine, OptionalEq]
  all_goals first | exact TermEq.refl _ | exact TermEq.addCommute h _ _

theorem associate (h : Spec.Derivation R associateLHS associateRHS)
    (a b c : Option (Term α)) :
    OptionalEq R (combine (combine a b) c) (combine a (combine b c)) := by
  cases a <;> cases b <;> cases c <;> simp only [combine, OptionalEq]
  all_goals first | trivial | exact TermEq.refl _ | exact TermEq.addAssociate h _ _ _

end OptionalEq

def fold (xs : List (Term α)) : Option (Term α) :=
  xs.foldr (fun x acc => combine (some x) acc) none

theorem fold_append {R : Spec.Assumptions ComputeStmt}
    (ha : Spec.Derivation R associateLHS associateRHS) (xs ys : List (Term α)) :
    OptionalEq R (fold (xs ++ ys)) (combine (fold xs) (fold ys)) := by
  induction xs with
  | nil => exact OptionalEq.refl _
  | cons x xs ih =>
    change OptionalEq R (combine (some x) (fold (xs ++ ys)))
      (combine (combine (some x) (fold xs)) (fold ys))
    exact (OptionalEq.congr (OptionalEq.refl _) ih).trans
      (OptionalEq.associate ha _ _ _).symm

theorem fold_perm {R : Spec.Assumptions ComputeStmt}
    (hc : Spec.Derivation R commuteLHS commuteRHS)
    (ha : Spec.Derivation R associateLHS associateRHS)
    {xs ys : List (Term α)} (hp : xs.Perm ys) : OptionalEq R (fold xs) (fold ys) := by
  induction hp with
  | nil => trivial
  | cons x _ ih => exact OptionalEq.congr (OptionalEq.refl _) ih
  | swap x y rest =>
    change OptionalEq R (combine (some y) (combine (some x) (fold rest)))
      (combine (some x) (combine (some y) (fold rest)))
    exact (OptionalEq.associate ha _ _ _).symm.trans
      ((OptionalEq.congr (OptionalEq.commute hc _ _) (OptionalEq.refl _)).trans
        (OptionalEq.associate ha _ _ _))
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

theorem SumTree.eval_fold {R : Spec.Assumptions ComputeStmt}
    (ha : Spec.Derivation R associateLHS associateRHS) (t : SumTree α) :
    OptionalEq R (some t.eval) (fold t.leaves) := by
  induction t with
  | leaf a => exact TermEq.refl a
  | join a b ih₁ ih₂ =>
    exact (OptionalEq.congr ih₁ ih₂).trans (fold_append ha _ _).symm

/-- Reordering or regrouping a reduction follows from the two scalar laws.
Every input and padding leaf occurs with the same multiplicity on both sides. -/
theorem SumTree.equiv_of_perm {R : Spec.Assumptions ComputeStmt}
    (hc : Spec.Derivation R commuteLHS commuteRHS)
    (ha : Spec.Derivation R associateLHS associateRHS)
    (a b : SumTree α) (hp : a.leaves.Perm b.leaves) : TermEq R a.eval b.eval :=
  (a.eval_fold ha).trans ((fold_perm hc ha hp).trans (b.eval_fold ha).symm)

end VeriTile.Triton.FP.Equational
